// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyTLL55jiKxPdZrbJqzo00gD_beuGZbas',
    appId: '1:7522216153:web:96bb37850f93f74a3676c8',
    messagingSenderId: '7522216153',
    projectId: 'mobile-dq',
    authDomain: 'mobile-dq.firebaseapp.com',
    storageBucket: 'mobile-dq.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmcWSb8I3QREGkYi3UKcs2iq45czDGAoY',
    appId: '1:7522216153:android:c8012a8cb606b5733676c8',
    messagingSenderId: '7522216153',
    projectId: 'mobile-dq',
    storageBucket: 'mobile-dq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfsL8oYE5DVXHUTlJEf4ciiFw1BEEsSOQ',
    appId: '1:7522216153:ios:c7c19836fd2a397c3676c8',
    messagingSenderId: '7522216153',
    projectId: 'mobile-dq',
    storageBucket: 'mobile-dq.appspot.com',
    iosClientId: '7522216153-0qbqs8bg7uvnuv4mgh6n7ghcm8lm2ad4.apps.googleusercontent.com',
    iosBundleId: 'com.fastcart.fastCart',
  );
}
